//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public int id { get; set; }
        public string MaNV { get; set; }
        public int Luong1 { get; set; }
        public int SoNgayCong { get; set; }
        public int SoNgayNghi { get; set; }
        public string Thang { get; set; }
        public string Nam { get; set; }
        public int BaoHiem { get; set; }
        public int SoGioLamThem { get; set; }
        public int PhuCap { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
