//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.LUONGs = new HashSet<LUONG>();
        }
    
        public string MaNV { get; set; }
        public string MaBoPhan { get; set; }
        public string Hoten { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string SDT { get; set; }
        public string TonGiao { get; set; }
        public string DiaChi { get; set; }
        public string QuocTich { get; set; }
        public string HocVan { get; set; }
        public System.DateTime NgayVaoLam { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BOPHAN BOPHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUONG> LUONGs { get; set; }
    }
}
