//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery_197PM33774
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAKEMANAGEMENTEntities : DbContext
    {
        public CAKEMANAGEMENTEntities()
            : base("name=CAKEMANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bunker> bunkers { get; set; }
        public virtual DbSet<cake> cakes { get; set; }
        public virtual DbSet<detail> details { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<kind> kinds { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
