//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery_197PM33774
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public Nullable<int> id_cake { get; set; }
        public int id_invoice { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual cake cake { get; set; }
        public virtual invoice invoice { get; set; }
    }
}
