//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVIen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public int id { get; set; }
        public string tua { get; set; }
        public string tacgia { get; set; }
        public string namxb { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> id_loai { get; set; }
    
        public virtual TheLoai TheLoai { get; set; }
    }
}
